/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mwanyasi;

/**
 *
 * @author John Mwanyambu
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class FinalProject extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FinalProject.class.getName());

    /**
     * Creates new form FinalProject
     */
    Connection cn;
    PreparedStatement pst;
    ResultSet rs;
    
    public FinalProject() {
        initComponents();
        myconnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idnumber = new javax.swing.JTextField();
        fees = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        firstrecord = new javax.swing.JButton();
        lastrecord = new javax.swing.JButton();
        nextrecord = new javax.swing.JButton();
        previousrecord = new javax.swing.JButton();
        displayrecords = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        displaytable = new javax.swing.JButton();
        printtable = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Student Information");

        jLabel2.setText("First Name");

        firstname.addActionListener(this::firstnameActionPerformed);

        jLabel3.setText("Last Name");

        jLabel4.setText("Gender");

        jLabel5.setText("ID Number");

        jLabel6.setText("Fees");

        submit.setText("submit");
        submit.addActionListener(this::submitActionPerformed);

        firstrecord.setText("FirstRecord");
        firstrecord.addActionListener(this::firstrecordActionPerformed);

        lastrecord.setText("LastRecord");
        lastrecord.addActionListener(this::lastrecordActionPerformed);

        nextrecord.setText("NextRecord");
        nextrecord.addActionListener(this::nextrecordActionPerformed);

        previousrecord.setText("PreviousRecord");
        previousrecord.addActionListener(this::previousrecordActionPerformed);

        displayrecords.setText("DisplayRecords");
        displayrecords.addActionListener(this::displayrecordsActionPerformed);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fisrt Name", "Last Name", "Gender", "ID Number", "Fees"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        displaytable.setText("DisplayTable");
        displaytable.addActionListener(this::displaytableActionPerformed);

        printtable.setText("PrintTable");
        printtable.addActionListener(this::printtableActionPerformed);

        jMenu1.setText("File");

        jMenuItem3.setText("save");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuItem12.setText("update");
        jMenuItem12.addActionListener(this::jMenuItem12ActionPerformed);
        jMenu1.add(jMenuItem12);

        jMenuItem13.setText("delete");
        jMenuItem13.addActionListener(this::jMenuItem13ActionPerformed);
        jMenu1.add(jMenuItem13);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Retrieve");

        jMenuItem1.setText("first Record");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu2.add(jMenuItem1);

        jMenuItem4.setText("last record");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("next record");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("previous record");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu2.add(jMenuItem6);

        jMenuItem8.setText("Display all");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Table");

        jMenuItem9.setText("show table");
        jMenuItem9.addActionListener(this::jMenuItem9ActionPerformed);
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Print");

        jMenuItem10.setText("print records");
        jMenuItem10.addActionListener(this::jMenuItem10ActionPerformed);
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("exit");

        jMenuItem11.setText("close file");
        jMenuItem11.addActionListener(this::jMenuItem11ActionPerformed);
        jMenu6.add(jMenuItem11);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(displayrecords)
                        .addGap(30, 30, 30)
                        .addComponent(displaytable))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(printtable)
                                .addGap(121, 121, 121))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                            .addGap(42, 42, 42)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                .addComponent(lastname)
                                                .addComponent(gender, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                .addComponent(fees)
                                                .addComponent(idnumber))
                                            .addGap(31, 31, 31))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(nextrecord)
                                            .addGap(70, 70, 70)
                                            .addComponent(previousrecord))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(submit)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(firstrecord)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lastrecord)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(idnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(fees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submit)
                            .addComponent(firstrecord)
                            .addComponent(lastrecord))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextrecord)
                            .addComponent(previousrecord))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displayrecords)
                            .addComponent(displaytable))
                        .addGap(18, 18, 18)
                        .addComponent(printtable)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        insertrecord();
    }//GEN-LAST:event_submitActionPerformed

    private void firstrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstrecordActionPerformed
        // TODO add your handling code here:
        getFirstRecord();
    }//GEN-LAST:event_firstrecordActionPerformed

    private void lastrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastrecordActionPerformed
        // TODO add your handling code here:
        getLastRecord();
    }//GEN-LAST:event_lastrecordActionPerformed

    private void nextrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextrecordActionPerformed
        // TODO add your handling code here:
        getNextRecord();
    }//GEN-LAST:event_nextrecordActionPerformed

    private void previousrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousrecordActionPerformed
        // TODO add your handling code here:
        getPreviousRecord();
    }//GEN-LAST:event_previousrecordActionPerformed

    private void displayrecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayrecordsActionPerformed
        // TODO add your handling code here:
        getDisplayRecords();
    }//GEN-LAST:event_displayrecordsActionPerformed

    private void displaytableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaytableActionPerformed
        // TODO add your handling code here:
        getTableRecords();
    }//GEN-LAST:event_displaytableActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        getRecord();
    }//GEN-LAST:event_tableMouseClicked

    private void printtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printtableActionPerformed
        // TODO add your handling code here:
        printing();
    }//GEN-LAST:event_printtableActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        insertrecord();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        getFirstRecord();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        getLastRecord();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        getNextRecord();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        getPreviousRecord();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        getDisplayRecords();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        getTableRecords();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        printing();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        updateRecord();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        deleteRecord();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FinalProject().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton displayrecords;
    private javax.swing.JButton displaytable;
    private javax.swing.JTextField fees;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton firstrecord;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField idnumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton lastrecord;
    private javax.swing.JButton nextrecord;
    private javax.swing.JButton previousrecord;
    private javax.swing.JButton printtable;
    private javax.swing.JButton submit;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void myconnection() {
        try{
            cn = DriverManager.getConnection("JDBC:MYSQL://LOCALHOST/STUDENT", "root", null);
            JOptionPane.showMessageDialog(null, "successfully connected");
            String sql = "select * from studentinfo";
            pst = cn.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = pst.executeQuery();
            
        }
        catch(Exception e){
            //System.out.println(e); //this is equivalent to to 
            e.printStackTrace();
        }
    }

    private void insertrecord() {
        try{
            pst = cn.prepareStatement("insert into studentinfo values (?,?,?,?,?)");
            pst.setString(1, firstname.getText());
            pst.setString(2, lastname.getText());
            pst.setString(3, gender.getText());
            pst.setString(4, idnumber.getText());
            pst.setString(5, fees.getText());
            
            pst.execute(); 
            //pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "record successfully submited");
            clear();
            new DemoForm().setVisible(true);
            dispose();
            
        }
        catch(Exception e){
            //System.out.println(e); //this is equivalent to to 
            e.printStackTrace();
        }
        
    }
    public void clear() {
        firstname.setText(null);
        lastname.setText(null);
        gender.setText(null);
        idnumber.setText(null);
        fees.setText(null);
    }

    private void getFirstRecord() {
        try {
            rs.first();
            for(int i=1; i<=5; i++) {
                System.out.print(rs.getString(i) + "\t");
                //display.append(rs.getString(i) + "\t");
            }
            System.out.println();
            
            
        }
        catch (Exception e){
            e.printStackTrace();
            //System.out.println(e); //this is equivalent to to 

            
        }
    }

    private void getLastRecord() {
        try {
            rs.last();
            for(int i=1; i<=5; i++) {
                System.out.print(rs.getString(i) + "\t");
                //display.append(rs.getString(i) + "\n");
            }
            System.out.println();
            
            
        }
        catch (Exception e){
            e.printStackTrace();
            //System.out.println(e); //this is equivalent to to 

            
        }
    }

    private void getNextRecord() {
        try {
            if (rs.next() == true) {
                for(int i=1; i<=5; i++) {
                    //String j = rs.getString(i);
                    System.out.print(rs.getString(i) + "\t");
                    //display.append(j + "\n");
                }
                System.out.println();
            }else
                rs.beforeFirst();
            
            
        }
        catch (Exception e){
            e.printStackTrace();
            //System.out.println(e); //this is equivalent to to 

            
        }
        
    }

    private void getPreviousRecord() {
        try {
            if (rs.previous() == true) {
                for(int i=1; i<=5; i++) {
                    System.out.print(rs.getString(i) + "\t");
                    //display.append(rs.getString(i) + "\n");
                }
                System.out.println();
            }else
                rs.afterLast();
            
            
        }
        catch (Exception e){
            e.printStackTrace();
            //System.out.println(e); //this is equivalent to to 

            
        }
    }

    private void getDisplayRecords() {
        try {
            myconnection();
            while (rs.next()) {
                for(int i=1; i<=5; i++) {
                    System.out.print(rs.getString(i) + "\t");
                    //display.append(rs.getString(i) + "\n");
                }
                System.out.println();
            }    
        }
        catch (Exception e){
            e.printStackTrace();
            //System.out.println(e); //this is equivalent to to 

            
        }
    }

    private void getTableRecords() {
        try {
            myconnection();
            DefaultTableModel model =(DefaultTableModel) table.getModel();
            //ResultSetMetadata rsmd = rs.getMetaData();
            //int n = rsmd.getColumnCount();
            //String[] data = new String[n];
            model.setRowCount(0);
            while (rs.next()){
                String[] data = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5) };
                //for (int i = 1; i <= n; i++){
                    //data[i] = rs.getString(i+1);
                //    
                    
                //}
                model.addRow(data);
                
            }
        }
        catch (Exception e){
            e.printStackTrace();
            //System.out.println(e); //this is equivalent to to 
            
        }
    }

    private void getRecord() {
        DefaultTableModel model =(DefaultTableModel) table.getModel();
        int n = table.getSelectedRow();
        firstname.setText((String) model.getValueAt(n, 0));
        lastname.setText((String) model.getValueAt(n, 1));
        gender.setText((String) model.getValueAt(n, 2));
        idnumber.setText((String)model.getValueAt(n, 3));
        fees.setText((String) model.getValueAt(n, 4));
    }

    private void printing() {
        try {
            getTableRecords();
            table.print();
        }
        catch(Exception ex) {
            System.out.println(ex);
        }
    }

    private void updateRecord() {
        try{
            pst = cn.prepareStatement("update studentinfo set firstname=?, lastname=?, gender=?, fees=? where idnumber=?");
            pst.setString(1, firstname.getText());
            pst.setString(2, lastname.getText());
            pst.setString(3, gender.getText());
            pst.setString(4, fees.getText());
            pst.setString(5, idnumber.getText());
            
            //pst.execute(); 
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "record successfully updated");
            clear();
            
        }
        catch(Exception e){
            //System.out.println(e); //this is equivalent to to 
            e.printStackTrace();
        }
        
    }

    private void deleteRecord() {
        try{
            pst = cn.prepareStatement("delete from studentinfo where idnumber=?");
            //pst.setString(1, firstname.getText());
            //pst.setString(2, lastname.getText());
            //pst.setString(3, gender.getText());
            //pst.setString(4, fees.getText());
            pst.setString(1, idnumber.getText());
            
            //pst.execute(); 
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "record successfully updated");
            clear();
            
        }
        catch(Exception e){
            //System.out.println(e); //this is equivalent to to 
            e.printStackTrace();
        }
        
    }
}
